using volleyhub_api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage;
using Npgsql;

namespace volleyhub_api.Ownership;

// Owns every piece of DDL in the system. public.account is bootstrapped with raw, idempotent SQL;
// the app schema (shared by every coach, rows split by ownerid) is created or column-synced straight
// from the EF model on every start, so a deploy that adds a column needs no migration step.
//
// Earlier versions gave each coach a tenant row and a schema of their own (tenant_<id>). Nothing
// here reads or drops those any more - public.tenant, public.account_tenant and the tenant_*
// schemas are left exactly as they were.
public class AppSchemaManager
{
    private readonly string _connectionString;

    public AppSchemaManager(IConfiguration config)
    {
        _connectionString = config["ConnectionStrings:dbCon"]!;
    }

    public async Task EnsureAccountSchema()
    {
        await using var conn = new NpgsqlConnection(_connectionString);
        await conn.OpenAsync();

        await using var cmd = conn.CreateCommand();
        cmd.CommandText = """
            CREATE TABLE IF NOT EXISTS public.account (
                accountid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                phone character varying(100) NOT NULL,
                passwordhash character varying(500) NOT NULL,
                name character varying(500),
                lastname character varying(250),
                firstname character varying(250),
                isactive boolean NOT NULL DEFAULT true,
                created timestamp with time zone NOT NULL DEFAULT now()
            );
            CREATE UNIQUE INDEX IF NOT EXISTS ux_account_phone ON public.account (btrim(phone));
            ALTER TABLE public.account ADD COLUMN IF NOT EXISTS photo text;
            ALTER TABLE public.account ADD COLUMN IF NOT EXISTS training_name character varying(200);
            ALTER TABLE public.account ADD COLUMN IF NOT EXISTS contactphone character varying(100);
            ALTER TABLE public.account ADD COLUMN IF NOT EXISTS bank_name character varying(100);
            ALTER TABLE public.account ADD COLUMN IF NOT EXISTS bank_account character varying(100);
            ALTER TABLE public.account ADD COLUMN IF NOT EXISTS bank_holder character varying(200);
            """;
        await cmd.ExecuteNonQueryAsync();
    }

    // The shared app schema: every table of VolleyDbContext, each with an ownerid column and index.
    public async Task EnsureAppSchema()
    {
        var schemaName = AppSchema.Name;
        await using var conn = new NpgsqlConnection(_connectionString);
        await conn.OpenAsync();

        await using (var createSchemaCmd = conn.CreateCommand())
        {
            createSchemaCmd.CommandText = $"CREATE SCHEMA IF NOT EXISTS \"{schemaName}\"";
            await createSchemaCmd.ExecuteNonQueryAsync();
        }

        var options = new DbContextOptionsBuilder<VolleyDbContext>().UseNpgsql(_connectionString).Options;
        await using var context = new VolleyDbContext(options, new FixedOwner(0));
        await CreateOrSyncContextAsync(conn, context, schemaName);

        // Every query is filtered by ownerid, so every table needs it indexed. CreateTablesAsync
        // makes these on a fresh database; this covers tables that were synced column by column.
        foreach (var table in context.Model.GetEntityTypes()
                     .Where(e => typeof(volleyhub_api.Model.IOwned).IsAssignableFrom(e.ClrType))
                     .Select(e => e.GetTableName()).Distinct())
        {
            await using var idx = conn.CreateCommand();
            idx.CommandText = $"CREATE INDEX IF NOT EXISTS \"IX_{table}_ownerid\" ON \"{schemaName}\".\"{table}\" (ownerid)";
            await idx.ExecuteNonQueryAsync();
        }
    }

    // Create this context's tables fresh when none exist yet, otherwise add whatever is missing.
    private static async Task CreateOrSyncContextAsync(NpgsqlConnection conn, DbContext context, string schemaName)
    {
        var tableNames = context.Model.GetEntityTypes()
            .Select(e => e.GetTableName())
            .Where(n => n is not null)
            .Distinct()
            .ToArray();

        long existing;
        await using (var checkCmd = conn.CreateCommand())
        {
            checkCmd.CommandText =
                "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = @schema AND table_name = ANY(@names)";
            checkCmd.Parameters.AddWithValue("schema", schemaName);
            checkCmd.Parameters.AddWithValue("names", tableNames!);
            existing = (long)(await checkCmd.ExecuteScalarAsync())!;
        }

        if (existing == 0)
        {
            var creator = context.GetInfrastructure().GetRequiredService<IRelationalDatabaseCreator>();
            await creator.CreateTablesAsync();
        }
        else
        {
            await SyncSchemaColumnsAsync(conn, context, schemaName);
        }
    }

    // Add missing tables/columns and drop the ones the model no longer has. A cheap stand-in for
    // migrations, which cannot express "one model, N schemas".
    private static async Task SyncSchemaColumnsAsync(NpgsqlConnection conn, DbContext context, string schemaName)
    {
        foreach (var entityType in context.Model.GetEntityTypes())
        {
            var tableName = entityType.GetTableName();
            if (tableName is null) continue;

            var storeObject = StoreObjectIdentifier.Table(tableName, schemaName);
            var pkProperties = entityType.FindPrimaryKey()?.Properties.ToHashSet() ?? [];

            var columns = new List<(string columnName, string storeType, bool isPk, bool isIdentity, bool isBool)>();
            foreach (var property in entityType.GetProperties())
            {
                var columnName = property.GetColumnName(storeObject);
                if (columnName is null) continue;

                var storeType = property.GetColumnType() ?? property.GetRelationalTypeMapping().StoreType;
                var isPk = pkProperties.Contains(property);
                var isIdentity = isPk && property.ValueGenerated == ValueGenerated.OnAdd;
                var isBool = property.ClrType == typeof(bool) && !property.IsNullable;

                columns.Add((columnName, storeType, isPk, isIdentity, isBool));
            }

            if (columns.Count == 0) continue;

            var columnDefs = columns.Select(col =>
            {
                var def = $"\"{col.columnName}\" {col.storeType}";
                if (col.isIdentity) def += " GENERATED BY DEFAULT AS IDENTITY";
                if (col.isBool) def += " NOT NULL DEFAULT false";
                return def;
            });
            var pkCols = columns.Where(col => col.isPk).Select(col => $"\"{col.columnName}\"");
            var pkClause = pkCols.Any() ? $", PRIMARY KEY ({string.Join(", ", pkCols)})" : "";

            await using (var createCmd = conn.CreateCommand())
            {
                createCmd.CommandText = $"""
                    CREATE TABLE IF NOT EXISTS "{schemaName}"."{tableName}" (
                        {string.Join(",\n    ", columnDefs)}{pkClause}
                    )
                    """;
                await createCmd.ExecuteNonQueryAsync();
            }

            foreach (var (columnName, storeType, _, _, isBool) in columns)
            {
                var boolConstraint = isBool ? " NOT NULL DEFAULT false" : "";
                await using var alterCmd = conn.CreateCommand();
                alterCmd.CommandText = $"""
                    ALTER TABLE "{schemaName}"."{tableName}"
                    ADD COLUMN IF NOT EXISTS "{columnName}" {storeType}{boolConstraint}
                    """;
                await alterCmd.ExecuteNonQueryAsync();
            }

            var dbColumns = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            await using (var colsCmd = conn.CreateCommand())
            {
                colsCmd.CommandText = """
                    SELECT column_name
                    FROM information_schema.columns
                    WHERE table_schema = @schema AND table_name = @table
                    """;
                colsCmd.Parameters.AddWithValue("schema", schemaName);
                colsCmd.Parameters.AddWithValue("table", tableName);
                await using var reader = await colsCmd.ExecuteReaderAsync();
                while (await reader.ReadAsync())
                    dbColumns.Add(reader.GetString(0));
            }

            var modelColumns = new HashSet<string>(
                columns.Select(col => col.columnName),
                StringComparer.OrdinalIgnoreCase);

            foreach (var staleCol in dbColumns.Except(modelColumns))
            {
                await using var dropCmd = conn.CreateCommand();
                dropCmd.CommandText = $"""
                    ALTER TABLE "{schemaName}"."{tableName}"
                    DROP COLUMN IF EXISTS "{staleCol}"
                    """;
                await dropCmd.ExecuteNonQueryAsync();
            }
        }
    }

}
