using volleyhub_api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage;
using Npgsql;

namespace volleyhub_api.Tenancy;

// Owns every piece of DDL in the system. The public schema is bootstrapped with raw, idempotent
// SQL (two EF contexts map public.tenant, so migration history would fight over it), and each club
// schema is created or column-synced straight from the EF model.
public class TenantSchemaManager
{
    private readonly string _connectionString;

    public TenantSchemaManager(IConfiguration config)
    {
        _connectionString = config["ConnectionStrings:dbCon"]!;
    }

    // public.tenant - the club registry.
    public async Task EnsureSharedSchema()
    {
        await using var conn = new NpgsqlConnection(_connectionString);
        await conn.OpenAsync();

        await using var cmd = conn.CreateCommand();
        cmd.CommandText = """
            CREATE TABLE IF NOT EXISTS public.tenant (
                tenantid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tenantname character varying(200) NOT NULL,
                isactive boolean NOT NULL DEFAULT true
            );
            ALTER TABLE public.tenant ADD COLUMN IF NOT EXISTS isactive boolean NOT NULL DEFAULT true;
            INSERT INTO public.tenant (tenantid, tenantname, isactive)
            VALUES (1, 'Demo Volleyball Club', true)
            ON CONFLICT DO NOTHING;
            SELECT setval(pg_get_serial_sequence('public.tenant', 'tenantid'),
                          GREATEST((SELECT COALESCE(MAX(tenantid), 0) FROM public.tenant), 1));
            """;
        await cmd.ExecuteNonQueryAsync();
    }

    // The public-schema identity layer: accounts, club membership, registration applications and
    // platform admins, plus the club profile columns.
    public async Task EnsureAccountSchema()
    {
        await using var conn = new NpgsqlConnection(_connectionString);
        await conn.OpenAsync();

        await using var cmd = conn.CreateCommand();
        cmd.CommandText = """
            CREATE TABLE IF NOT EXISTS public.account (
                accountid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                phone character varying(100) NOT NULL,
                passwordhash character varying(500) NOT NULL,
                name character varying(500),
                lastname character varying(250),
                firstname character varying(250),
                isactive boolean NOT NULL DEFAULT true,
                created timestamp with time zone NOT NULL DEFAULT now()
            );
            CREATE UNIQUE INDEX IF NOT EXISTS ux_account_phone ON public.account (btrim(phone));
            ALTER TABLE public.account ADD COLUMN IF NOT EXISTS photo text;

            CREATE TABLE IF NOT EXISTS public.account_tenant (
                accounttenantid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                accountid integer NOT NULL,
                tenantid integer NOT NULL,
                role character varying(20) NOT NULL DEFAULT 'player',
                status character varying(20) NOT NULL DEFAULT 'active',
                staffid integer NOT NULL DEFAULT 0,
                joined timestamp with time zone NOT NULL DEFAULT now()
            );
            CREATE UNIQUE INDEX IF NOT EXISTS ux_account_tenant ON public.account_tenant (accountid, tenantid);

            CREATE TABLE IF NOT EXISTS public.platform_admin (
                platformadminid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                accountid integer NOT NULL,
                phone character varying(100) NOT NULL,
                created timestamp with time zone NOT NULL DEFAULT now()
            );
            CREATE UNIQUE INDEX IF NOT EXISTS ux_platform_admin_account ON public.platform_admin (accountid);

            CREATE TABLE IF NOT EXISTS public.tenant_request (
                tenantrequestid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                accountid integer NOT NULL,
                tenantname character varying(200) NOT NULL,
                registernumber character varying(100),
                address character varying(500),
                contactphone character varying(100),
                status character varying(20) NOT NULL DEFAULT 'pending',
                note character varying(500),
                tenantid integer,
                reviewedby integer,
                reviewedat timestamp with time zone,
                created timestamp with time zone NOT NULL DEFAULT now()
            );
            CREATE INDEX IF NOT EXISTS ix_tenant_request_status ON public.tenant_request (status);
            ALTER TABLE public.tenant_request ADD COLUMN IF NOT EXISTS logo text;
            ALTER TABLE public.tenant_request ADD COLUMN IF NOT EXISTS email character varying(100);
            ALTER TABLE public.tenant_request ADD COLUMN IF NOT EXISTS tagline character varying(500);

            ALTER TABLE public.tenant ADD COLUMN IF NOT EXISTS registernumber character varying(100);
            ALTER TABLE public.tenant ADD COLUMN IF NOT EXISTS address character varying(500);
            ALTER TABLE public.tenant ADD COLUMN IF NOT EXISTS contactphone character varying(100);
            ALTER TABLE public.tenant ADD COLUMN IF NOT EXISTS logo text;
            ALTER TABLE public.tenant ADD COLUMN IF NOT EXISTS locale character varying(10);
            ALTER TABLE public.tenant ADD COLUMN IF NOT EXISTS currency character varying(3);
            ALTER TABLE public.tenant ADD COLUMN IF NOT EXISTS createdby integer;
            ALTER TABLE public.tenant ADD COLUMN IF NOT EXISTS created timestamp with time zone;
            CREATE UNIQUE INDEX IF NOT EXISTS ux_tenant_name ON public.tenant (lower(btrim(tenantname)));

            -- Public profile of a training centre: what the directory on the public site shows.
            ALTER TABLE public.tenant ADD COLUMN IF NOT EXISTS tagline character varying(500);
            ALTER TABLE public.tenant ADD COLUMN IF NOT EXISTS description text;
            ALTER TABLE public.tenant ADD COLUMN IF NOT EXISTS cover text;
            ALTER TABLE public.tenant ADD COLUMN IF NOT EXISTS photos text;
            ALTER TABLE public.tenant ADD COLUMN IF NOT EXISTS city character varying(100);
            ALTER TABLE public.tenant ADD COLUMN IF NOT EXISTS district character varying(100);
            ALTER TABLE public.tenant ADD COLUMN IF NOT EXISTS email character varying(100);
            ALTER TABLE public.tenant ADD COLUMN IF NOT EXISTS website character varying(300);
            ALTER TABLE public.tenant ADD COLUMN IF NOT EXISTS facebook character varying(300);
            ALTER TABLE public.tenant ADD COLUMN IF NOT EXISTS instagram character varying(300);
            ALTER TABLE public.tenant ADD COLUMN IF NOT EXISTS price_from numeric;
            ALTER TABLE public.tenant ADD COLUMN IF NOT EXISTS age_from integer;
            ALTER TABLE public.tenant ADD COLUMN IF NOT EXISTS age_to integer;
            ALTER TABLE public.tenant ADD COLUMN IF NOT EXISTS latitude double precision;
            ALTER TABLE public.tenant ADD COLUMN IF NOT EXISTS longitude double precision;
            ALTER TABLE public.tenant ADD COLUMN IF NOT EXISTS is_published boolean NOT NULL DEFAULT false;

            -- Platform content. Deliberately in the public schema: news and the shop belong to the
            -- platform, not to any one training centre.
            CREATE TABLE IF NOT EXISTS public.news_post (
                newsid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title character varying(300) NOT NULL,
                summary character varying(1000),
                body text,
                cover text,
                category smallint NOT NULL DEFAULT 2,
                source character varying(200),
                source_url character varying(500),
                published_at timestamp with time zone,
                author_accountid integer,
                view_count integer NOT NULL DEFAULT 0,
                is_deleted boolean NOT NULL DEFAULT false,
                created timestamp with time zone NOT NULL DEFAULT now(),
                updated timestamp with time zone NOT NULL DEFAULT now()
            );
            CREATE INDEX IF NOT EXISTS ix_news_published ON public.news_post (published_at DESC);

            CREATE TABLE IF NOT EXISTS public.product (
                productid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name character varying(300) NOT NULL,
                category character varying(100),
                brand character varying(200),
                description text,
                price numeric NOT NULL DEFAULT 0,
                old_price numeric,
                images text,
                stock integer NOT NULL DEFAULT 0,
                isactive boolean NOT NULL DEFAULT true,
                sort_order integer NOT NULL DEFAULT 0,
                is_deleted boolean NOT NULL DEFAULT false,
                created timestamp with time zone NOT NULL DEFAULT now(),
                updated timestamp with time zone NOT NULL DEFAULT now()
            );
            CREATE INDEX IF NOT EXISTS ix_product_category ON public.product (category);

            CREATE TABLE IF NOT EXISTS public.product_order (
                orderid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                accountid integer NOT NULL DEFAULT 0,
                customer_name character varying(200) NOT NULL,
                phone character varying(100) NOT NULL,
                address character varying(500),
                note character varying(1000),
                total numeric NOT NULL DEFAULT 0,
                status smallint NOT NULL DEFAULT 1,
                admin_note character varying(500),
                is_deleted boolean NOT NULL DEFAULT false,
                created timestamp with time zone NOT NULL DEFAULT now(),
                updated timestamp with time zone NOT NULL DEFAULT now()
            );
            CREATE INDEX IF NOT EXISTS ix_product_order_status ON public.product_order (status, created DESC);

            CREATE TABLE IF NOT EXISTS public.product_order_item (
                orderitemid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                orderid bigint NOT NULL,
                productid bigint NOT NULL,
                product_name character varying(300) NOT NULL,
                price numeric NOT NULL DEFAULT 0,
                quantity integer NOT NULL DEFAULT 1
            );
            CREATE INDEX IF NOT EXISTS ix_product_order_item_order ON public.product_order_item (orderid);
            """;
        await cmd.ExecuteNonQueryAsync();
    }

    public Task CreateSchemaForTenant(string schemaName, int tenantId)
        => CreateSchemaForTenant(schemaName, tenantId, seedDemoData: true);

    // Self-service club creation passes seedDemoData:false - tables and reference data only. The
    // creator is added as Admin separately via ProvisionStaff.
    public async Task CreateSchemaForTenant(string schemaName, int tenantId, bool seedDemoData)
    {
        await using var conn = new NpgsqlConnection(_connectionString);
        await conn.OpenAsync();

        await using (var createSchemaCmd = conn.CreateCommand())
        {
            createSchemaCmd.CommandText = $"CREATE SCHEMA IF NOT EXISTS \"{schemaName}\"";
            await createSchemaCmd.ExecuteNonQueryAsync();
        }

        var options = new DbContextOptionsBuilder<VolleyDbContext>()
            .UseNpgsql(_connectionString)
            .ReplaceService<IModelCacheKeyFactory, SchemaAwareModelCacheKeyFactory>()
            .Options;
        await using (var context = new VolleyDbContext(options, new FixedTenantProvider(schemaName)))
        {
            await CreateOrSyncContextAsync(conn, context, schemaName);
        }

        await SeedSchemaDataAsync(conn, schemaName, seedDemoData);
    }

    // Insert (or reuse) one staff row inside tenant_<id> for an account, returning its staffid.
    // Idempotent on (phone, tenantid) so a retry never duplicates.
    public async Task<int> ProvisionStaff(string schemaName, int tenantId, string phone, string? name,
        string encryptedPassword, int roleid, string? lastname = null, string? firstname = null, int accountId = 0)
    {
        await using var conn = new NpgsqlConnection(_connectionString);
        await conn.OpenAsync();

        await using (var check = conn.CreateCommand())
        {
            check.CommandText = $"SELECT staffid FROM \"{schemaName}\".\"staff\" WHERE phone = @phone AND tenantid = @tid LIMIT 1";
            check.Parameters.AddWithValue("phone", phone);
            check.Parameters.AddWithValue("tid", tenantId);
            var existing = await check.ExecuteScalarAsync();
            if (existing != null && existing != DBNull.Value)
                return Convert.ToInt32(existing);
        }

        await using (var ins = conn.CreateCommand())
        {
            ins.CommandText = $"""
                INSERT INTO "{schemaName}"."staff"
                    (accountid, phone, staffname, lastname, firstname, password, isactive, roleid, tenantid, created)
                VALUES (@acc, @phone, @name, @lastname, @firstname, @pwd, true, @role, @tid, now())
                RETURNING staffid
                """;
            ins.Parameters.AddWithValue("acc", accountId);
            ins.Parameters.AddWithValue("phone", phone);
            ins.Parameters.AddWithValue("name", (object?)name ?? DBNull.Value);
            ins.Parameters.AddWithValue("lastname", (object?)lastname ?? DBNull.Value);
            ins.Parameters.AddWithValue("firstname", (object?)firstname ?? DBNull.Value);
            ins.Parameters.AddWithValue("pwd", encryptedPassword);
            ins.Parameters.AddWithValue("role", roleid);
            ins.Parameters.AddWithValue("tid", tenantId);
            var id = await ins.ExecuteScalarAsync();
            return Convert.ToInt32(id);
        }
    }

    // Create this context's tables fresh when none exist yet, otherwise add whatever is missing.
    private static async Task CreateOrSyncContextAsync(NpgsqlConnection conn, DbContext context, string schemaName)
    {
        var tableNames = context.Model.GetEntityTypes()
            .Select(e => e.GetTableName())
            .Where(n => n is not null)
            .Distinct()
            .ToArray();

        long existing;
        await using (var checkCmd = conn.CreateCommand())
        {
            checkCmd.CommandText =
                "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = @schema AND table_name = ANY(@names)";
            checkCmd.Parameters.AddWithValue("schema", schemaName);
            checkCmd.Parameters.AddWithValue("names", tableNames!);
            existing = (long)(await checkCmd.ExecuteScalarAsync())!;
        }

        if (existing == 0)
        {
            var creator = context.GetInfrastructure().GetRequiredService<IRelationalDatabaseCreator>();
            await creator.CreateTablesAsync();
        }
        else
        {
            await SyncSchemaColumnsAsync(conn, context, schemaName);
        }
    }

    // Add missing tables/columns and drop the ones the model no longer has. A cheap stand-in for
    // migrations, which cannot express "one model, N schemas".
    private static async Task SyncSchemaColumnsAsync(NpgsqlConnection conn, DbContext context, string schemaName)
    {
        foreach (var entityType in context.Model.GetEntityTypes())
        {
            var tableName = entityType.GetTableName();
            if (tableName is null) continue;

            var storeObject = StoreObjectIdentifier.Table(tableName, schemaName);
            var pkProperties = entityType.FindPrimaryKey()?.Properties.ToHashSet() ?? [];

            var columns = new List<(string columnName, string storeType, bool isPk, bool isIdentity, bool isBool)>();
            foreach (var property in entityType.GetProperties())
            {
                var columnName = property.GetColumnName(storeObject);
                if (columnName is null) continue;

                var storeType = property.GetColumnType() ?? property.GetRelationalTypeMapping().StoreType;
                var isPk = pkProperties.Contains(property);
                var isIdentity = isPk && property.ValueGenerated == ValueGenerated.OnAdd;
                var isBool = property.ClrType == typeof(bool) && !property.IsNullable;

                columns.Add((columnName, storeType, isPk, isIdentity, isBool));
            }

            if (columns.Count == 0) continue;

            var columnDefs = columns.Select(col =>
            {
                var def = $"\"{col.columnName}\" {col.storeType}";
                if (col.isIdentity) def += " GENERATED BY DEFAULT AS IDENTITY";
                if (col.isBool) def += " NOT NULL DEFAULT false";
                return def;
            });
            var pkCols = columns.Where(col => col.isPk).Select(col => $"\"{col.columnName}\"");
            var pkClause = pkCols.Any() ? $", PRIMARY KEY ({string.Join(", ", pkCols)})" : "";

            await using (var createCmd = conn.CreateCommand())
            {
                createCmd.CommandText = $"""
                    CREATE TABLE IF NOT EXISTS "{schemaName}"."{tableName}" (
                        {string.Join(",\n    ", columnDefs)}{pkClause}
                    )
                    """;
                await createCmd.ExecuteNonQueryAsync();
            }

            foreach (var (columnName, storeType, _, _, isBool) in columns)
            {
                var boolConstraint = isBool ? " NOT NULL DEFAULT false" : "";
                await using var alterCmd = conn.CreateCommand();
                alterCmd.CommandText = $"""
                    ALTER TABLE "{schemaName}"."{tableName}"
                    ADD COLUMN IF NOT EXISTS "{columnName}" {storeType}{boolConstraint}
                    """;
                await alterCmd.ExecuteNonQueryAsync();
            }

            var dbColumns = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            await using (var colsCmd = conn.CreateCommand())
            {
                colsCmd.CommandText = """
                    SELECT column_name
                    FROM information_schema.columns
                    WHERE table_schema = @schema AND table_name = @table
                    """;
                colsCmd.Parameters.AddWithValue("schema", schemaName);
                colsCmd.Parameters.AddWithValue("table", tableName);
                await using var reader = await colsCmd.ExecuteReaderAsync();
                while (await reader.ReadAsync())
                    dbColumns.Add(reader.GetString(0));
            }

            var modelColumns = new HashSet<string>(
                columns.Select(col => col.columnName),
                StringComparer.OrdinalIgnoreCase);

            foreach (var staleCol in dbColumns.Except(modelColumns))
            {
                await using var dropCmd = conn.CreateCommand();
                dropCmd.CommandText = $"""
                    ALTER TABLE "{schemaName}"."{tableName}"
                    DROP COLUMN IF EXISTS "{staleCol}"
                    """;
                await dropCmd.ExecuteNonQueryAsync();
            }
        }
    }

    // Reference data (roles) is always seeded; demo business data only for the demo club.
    private static async Task SeedSchemaDataAsync(NpgsqlConnection conn, string s, bool seedDemoData)
    {
        await using (var roles = conn.CreateCommand())
        {
            roles.CommandText = $"""
                INSERT INTO "{s}"."role" (roleid, rolename) VALUES
                    (1, 'Admin'), (2, 'Manager'), (3, 'Coach'), (4, 'Staff')
                ON CONFLICT (roleid) DO NOTHING;
                SELECT setval(pg_get_serial_sequence('"{s}"."role"', 'roleid'),
                              GREATEST((SELECT COALESCE(MAX(roleid), 0) FROM "{s}"."role"), 1));
                """;
            await roles.ExecuteNonQueryAsync();
        }

        if (!seedDemoData) return;

        // A centre with no hall cannot schedule anything, so the demo tenant gets one to make the
        // schedule screens usable straight after a fresh install.
        await using (var venue = conn.CreateCommand())
        {
            venue.CommandText = $"""
                INSERT INTO "{s}"."venue" (name, courts, is_deleted, created, updated)
                SELECT 'Үндсэн заал', 1, false, now(), now()
                WHERE NOT EXISTS (SELECT 1 FROM "{s}"."venue")
                """;
            await venue.ExecuteNonQueryAsync();
        }
    }
}
